// `npm run setup` — create local .env files with generated dev values.
// NEVER overwrites an existing .env. Values written here are local-dev only
// and are gitignored.
import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dbPassword = randomBytes(16).toString('hex');

const rootEnvPath = path.join(root, '.env');
if (existsSync(rootEnvPath)) {
  console.info('[setup] .env already exists — leaving it untouched.');
} else {
  const rootEnv = `# Local development environment (generated by npm run setup).
# Gitignored — never commit real values. See docs/environment.md.
NODE_ENV=development

# --- Database (embedded Postgres started by npm run db:dev) ---
DATABASE_URL=postgres://veltrix:${dbPassword}@127.0.0.1:5433/veltrixeye
DATABASE_SSL_MODE=disable
DATABASE_POOL_MAX=10

# --- API ---
PORT=4000
HOST=0.0.0.0
SESSION_TTL_DAYS=30
LOG_LEVEL=info
`;
  writeFileSync(rootEnvPath, rootEnv);
  console.info('[setup] created .env (local development values)');
}

const webEnvPath = path.join(root, 'apps', 'web', '.env.local');
if (existsSync(webEnvPath)) {
  console.info('[setup] apps/web/.env.local already exists — leaving it untouched.');
} else {
  const webEnv = `# Local development environment for the web app (generated by npm run setup).
WEB_PORT=3000
# Internal (server-side) address of the API. The web app proxies /api/* here.
API_INTERNAL_BASE=http://127.0.0.1:4000
`;
  writeFileSync(webEnvPath, webEnv);
  console.info('[setup] created apps/web/.env.local (local development values)');
}
console.info('[setup] done. Start development with: npm run dev');
